[package]
name = "kio-pipeline"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
cap-primitives.workspace = true
getrandom.workspace = true
kio-adapter = { path = "../kio-adapter" }
kio-core.workspace = true
rusqlite = { workspace = true, features = ["serialize"] }
serde.workspace = true
serde_json.workspace = true
serde_jcs.workspace = true
sha2.workspace = true
thiserror.workspace = true
tempfile = "3"
toml.workspace = true
unicode-normalization.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[dev-dependencies]
