[package]
name = "kio-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
jsonschema.workspace = true
serde.workspace = true
serde_jcs.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
toml.workspace = true
unicode-normalization.workspace = true
unicode-case-mapping.workspace = true
unicode-general-category.workspace = true

[target.'cfg(unix)'.dependencies]
cap-primitives.workspace = true
libc = "0.2"

[target.'cfg(windows)'.dependencies]
cap-primitives.workspace = true
windows-sys.workspace = true

[dev-dependencies]
tempfile = "3"
